/**
 * Notion Built-In SVG Icon -> Emoji Mapping
 *
 * Maps ~900+ Notion built-in icon names (from their S3/CDN SVG files) to
 * Unicode emoji equivalents. Notion icons are single-color flat SVGs with
 * filenames like `briefcase_gray.svg`. This map strips the color suffix
 * and maps the base name to the closest emoji.
 *
 * Source: https://www.files2notion.com/free-tools/icons
 * Notion API icon types: emoji, file, external, custom_emoji
 *
 * @see https://developers.notion.com/reference/emoji-object
 */

/** Base icon name -> emoji. Keys are lowercase hyphenated (e.g. "arrow-up"). */
const ICON_MAP: Record<string, string> = {
  // ── Numbers & Symbols ─────────────────────────────
  '123': '🔢',
  asterisk: '✳️',
  'star-of-life': '✳️',
  hashtag: '#️⃣',
  numero: '#️⃣',
  infinity: '♾️',
  'fleur-de-lis': '⚜️',
  'yin-yang': '☯️',
  peace: '☮️',
  'looped-square': '🔲',

  // ── Arrows & Navigation ───────────────────────────
  'arrow-circle-down': '⬇️',
  'arrow-down-basic': '⬇️',
  'arrow-down': '⬇️',
  downward: '⬇️',
  'arrow-down-line': '⬇️',
  'arrow-left-basic': '⬅️',
  'arrow-left': '⬅️',
  backward: '⬅️',
  'arrow-left-line': '⬅️',
  'arrow-northeast': '↗️',
  'arrow-northwest': '↖️',
  'arrow-right-basic': '➡️',
  'arrow-right': '➡️',
  forward: '➡️',
  'arrow-right-line': '➡️',
  'arrow-southeast': '↘️',
  'arrow-southwest': '↙️',
  'arrow-turn-left': '↩️',
  'arrow-turn-right': '↪️',
  'arrow-up-basic': '⬆️',
  'arrow-up': '⬆️',
  upward: '⬆️',
  'arrow-up-line': '⬆️',
  'arrows-horizontal': '\u2194️',
  'arrows-vertical': '↕️',
  'arrows-swap-horizontally': '🔀',
  'arrows-swap-vertically': '🔀',
  'circle-arrows-horizontal': '🔄',
  'circle-arrows-vertical': '🔄',
  bounce: '🔃',
  condense: '🔽',
  expand: '🔼',
  merge: '🔀',
  'swap-horizontally': '🔀',
  'swap-vertically': '🔀',
  directions: '🧭',
  redirect: '↪️',
  'send-to': '📤',
  undo: '↩️',
  redo: '↪️',
  refresh: '🔃',
  'refresh-reverse': '🔄',
  repeat: '🔁',
  shuffle: '🔀',
  sync: '🔄',
  'sync-reverse': '🔄',
  transfers: '🔄',

  // ── User Actions & Interface ──────────────────────
  'log-in': '🔑',
  'sign-in': '🔑',
  'log-out': '🚪',
  'sign-out': '🚪',
  share: '🔗',
  save: '💾',
  reply: '↩️',
  'reply-all': '↩️',
  promoted: '⭐',
  send: '📤',
  eject: '⏏️',
  exit: '🚪',
  follow: '👣',
  unfollow: '🚫',
  close: '✖️',
  clear: '🧹',
  'browser-stop': '🛑',
  cursor: '🖱️',
  'cursor-button': '🖱️',
  'cursor-click': '🖱️',
  rename: '✏️',
  more: '⋯',
  reorder: '↕️',
  crop: '✂️',
  filtered: '🔽',
  search: '🔍',
  'zoom-in': '🔍',
  'zoom-out': '🔎',
  view: '👁️',
  'view-off': '🙈',
  preview: '👁️',

  // ── Communication ─────────────────────────────────
  mail: '📧',
  invitation: '📧',
  comment: '💬',
  chat: '💬',
  conversation: '💬',
  dialogue: '💬',
  'thought-dialogue': '💭',
  thought: '💭',
  thinking: '💭',
  notification: '🔔',
  bell: '🔔',
  'bell-notification': '🔔',
  'bell-off': '🔕',
  'phone-call': '📞',
  'phone-end-call': '📵',
  'phone-speaker': '📱',
  phone: '📱',
  voicemail: '📬',
  megaphone: '📢',
  feed: '📡',

  // ── Documents & Files ─────────────────────────────
  document: '📄',
  'move-document': '📄',
  'upload-document': '📄',
  'new-document': '📄',
  'official-document': '📜',
  'signature-document': '📝',
  clipping: '📎',
  'compressed-document': '🗜️',
  copy: '📋',
  paste: '📋',
  description: '📝',
  news: '📰',
  postcard: '📮',
  'postage-stamp': '📮',
  receipt: '🧾',
  reference: '📑',
  script: '📜',
  attachment: '📎',

  // ── Folders ───────────────────────────────────────
  folder: '📁',
  move: '📂',
  'upload-folder': '📂',
  'new-folder': '📁',

  // ── Data & Charts ─────────────────────────────────
  chart: '📊',
  'chart-area': '📈',
  'chart-alternate': '📊',
  'chart-mixed': '📊',
  'chart-donut': '🍩',
  'chart-line': '📈',
  'chart-pie': '📊',
  subtask: '📋',
  timeline: '📅',
  activity: '📈',
  dashboard: '📊',
  formula: '🧮',
  mathematics: '🧮',
  database: '🗄️',
  layers: '📚',
  table: '📊',
  row: '📊',
  column: '📊',
  grid: '🔲',
  'grid-dense': '🔲',
  'grid-wide': '🔲',
  'grid-wide-six': '🔲',

  // ── Checkmarks & Status ───────────────────────────
  check: '✅',
  checkmark: '✅',
  'checkmark-line': '✅',
  'checkmark-square': '☑️',
  checklist: '✅',
  verified: '✅',
  'do-not-disturb': '🚫',
  no: '🚫',
  'no-entry': '⛔',

  // ── Priority & Alerts ─────────────────────────────
  'priority-low': '🔽',
  'priority-mid': '➖',
  'priority-high': '🔺',
  'chevrons-vertical': '↕️',
  'exclamation-mark': '❗',
  'exclamation-mark-double': '‼️',
  report: '📋',
  'new-alert': '🆕',
  error: '❌',
  alert: '🚨',
  'thought-alert': '💭',
  warning: '⚠️',
  'info-alternate': 'ℹ️',
  'question-mark': '❓',
  'help-alternate': '❓',

  // ── Shapes - Circles ──────────────────────────────
  circle: '⚪',
  'circle-alternate': '⚪',
  'circle-dashed': '⚪',
  'circle-remove': '⊘',
  'circle-dot': '⊙',
  'circle-one-eighth': '◔',
  'circle-two-eighths': '◔',
  'circle-three-eighths': '◑',
  'circle-four-eighths': '◑',
  'circle-five-eighths': '◕',
  'circle-six-eighths': '◕',
  'circle-seven-eighths': '⬤',

  // ── Shapes - Squares ──────────────────────────────
  square: '🟦',
  'square-alternate': '🟦',
  'square-dashed': '🟦',
  'square-one-fourth': '🟦',
  'square-two-fourths': '🟦',
  'square-three-fourths': '🟦',
  dependency: '🔗',

  // ── Shapes - Triangles ────────────────────────────
  triangle: '🔺',
  'triangle-alternate': '🔺',
  'triangle-dashed': '🔺',
  'triangle-one-third': '🔺',
  'triangle-two-thirds': '🔺',

  // ── Shapes - Pentagons ────────────────────────────
  pentagon: '⬠',
  'pentagon-alternate': '⬠',
  'pentagon-dashed': '⬠',
  'pentagon-one-fifth': '⬠',
  'pentagon-two-fifths': '⬠',
  'pentagon-three-fifths': '⬠',
  'pentagon-four-fifths': '⬠',

  // ── Shapes - Hexagons ─────────────────────────────
  hexagon: '⬡',
  'hexagon-alternate': '⬡',
  'hexagon-dashed': '⬡',
  'hexagon-one-sixth': '⬡',
  'hexagon-two-sixths': '⬡',
  'hexagon-three-sixths': '⬡',
  'hexagon-four-sixths': '⬡',
  'hexagon-five-sixths': '⬡',

  // ── Shapes - Other ────────────────────────────────
  octagon: '🛑',
  orbit: '🪐',

  // ── People & Body ─────────────────────────────────
  user: '👤',
  'user-circle': '👤',
  'user-circle-filled': '👤',
  'user-circle-dashed': '👤',
  'chat-user': '🗣️',
  'tabs-user': '👤',
  people: '👫',
  friends: '👫',
  groups: '👥',
  following: '👥',
  sharing: '🤝',
  'service-counter': '🛎️',
  meeting: '🤝',
  public: '🌐',
  'person-feminine': '👩',
  'person-masculine': '👨',
  profile: '👤',
  username: '👤',
  baby: '👶',
  child: '🧒',
  'vitruvian-man': '🧍',
  hand: '✋',
  ear: '👂',
  'ear-hearing-aid': '🦻',
  mouth: '👄',
  brain: '🧠',
  throat: '🫁',
  lungs: '🫁',
  stomach: '🫃',
  bone: '🦴',
  'long-bone': '🦴',
  skull: '💀',
  'skull-profile': '💀',
  tooth: '🦷',
  dental: '🦷',

  // ── Accessibility ─────────────────────────────────
  accessibility: '♿',
  'wheelchair-access': '♿',
  wheelchair: '♿',
  'wheelchair-motorized': '♿',

  // ── Emojis & Faces ────────────────────────────────
  emoji: '😊',
  'emoji-angry': '😠',
  'emoji-disappointed': '😞',
  'emoji-sad': '😢',
  'emoji-big-sad': '😭',
  'emoji-surprised': '😮',
  'emoji-grinning': '😀',
  'emoji-grinning-smiling-eyes': '😄',
  'emoji-heart-eyes': '😍',
  'emoji-neutral': '😐',
  'emoji-smiling-eyes': '😊',
  'emoji-sunglasses': '😎',
  'emoji-winking': '😉',
  alien: '👽',
  'alien-pixel': '👾',
  ghost: '👻',
  robot: '🤖',

  // ── Hearts & Emotions ─────────────────────────────
  heart: '❤️',
  'heart-outline': '🤍',
  'heart-box-bow': '💝',
  heartbroken: '💔',
  'heart-rate': '💓',
  'heart-rate-monitor': '💓',
  defibrillator: '🏥',
  'thumbs-up': '👍',
  'thumbs-down': '👎',

  // ── Travel & Transportation ───────────────────────
  airplane: '✈️',
  arrivals: '🛬',
  departures: '🛫',
  'connecting-flight': '✈️',
  customs: '🛃',
  immigration: '🛂',
  car: '🚗',
  taxi: '🚕',
  bus: '🚌',
  'bus-double-decker': '🚌',
  'bus-metro': '🚍',
  train: '🚆',
  'train-high-speed': '🚄',
  'train-light-rail': '🚈',
  'train-magnetic-levitation': '🚅',
  'train-metro': '🚇',
  monorail: '🚝',
  helicopter: '🚁',
  'hot-air-balloon': '🎈',
  rocket: '🚀',
  sailboat: '⛵',
  boat: '⛵',
  scooter: '🛴',
  motorcycle: '🏍️',
  bicycle: '🚲',
  skateboard: '🛹',
  'ice-skate': '⛸️',
  'inline-skate': '🛼',
  'roller-skate': '🛼',
  ambulance: '🚑',
  'fire-truck': '🚒',
  truck: '🚚',
  'delivery-truck': '🚚',
  escalator: '🛗',
  elevator: '🛗',
  parking: '🅿️',
  'parking-no': '🚫',
  fuel: '⛽',
  anchor: '⚓',
  compass: '🧭',
  map: '🗺️',
  'map-pin': '📍',
  'map-pin-alternate': '📍',
  location: '📍',
  navigation: '🧭',
  globe: '🌍',
  geography: '🌍',
  'directional-sign': '🪧',
  'directional-sign-left': '🪧',
  'directional-sign-right': '🪧',
  passport: '🛂',
  luggage: '🧳',
  'luggage-cart': '🧳',
  'baggage-claim': '🛄',
  'boarding-pass': '🎫',
  ticket: '🎫',
  'ticket-admission': '🎟️',

  // ── Home & Furniture ──────────────────────────────
  home: '🏠',
  bed: '🛏️',
  'bunk-bed': '🛏️',
  couch: '🛋️',
  chair: '🪑',
  bathtub: '🛁',
  'bathtub-shower': '🛁',
  shower: '🚿',
  sink: '🚰',
  toilet: '🚽',
  'toilet-paper': '🧻',
  towel: '🧖',
  lounge: '🛋️',
  door: '🚪',
  key: '🔑',
  'key-antique': '🗝️',
  lock: '🔒',
  'lock-keyhole': '🔒',
  unlock: '🔓',
  'unlock-keyhole': '🔓',

  // ── Food ──────────────────────────────────────────
  apple: '🍎',
  avocado: '🥑',
  banana: '🍌',
  bread: '🍞',
  broccoli: '🥦',
  burger: '🍔',
  cake: '🎂',
  candy: '🍬',
  carrot: '🥕',
  cherries: '🍒',
  chicken: '🍗',
  'chili-pepper': '🌶️',
  corn: '🌽',
  cupcake: '🧁',
  egg: '🥚',
  garlic: '🧄',
  grapes: '🍇',
  lemon: '🍋',
  meat: '🥩',
  mushroom: '🍄',
  onion: '🧅',
  orange: '🍊',
  peanut: '🥜',
  pear: '🍐',
  pizza: '🍕',
  'plate-food': '🍽️',
  poultry: '🍗',
  pretzel: '🥨',
  sandwich: '🥪',
  strawberry: '🍓',
  wheat: '🌾',
  bowl: '🥣',
  'bowl-food': '🥣',
  pot: '🍲',
  'frying-pan': '🍳',
  fork: '🍴',
  'fork-and-knife': '🍴',
  dining: '🍽️',
  flatware: '🍴',
  spoon: '🥄',
  knife: '🔪',
  'knife-kitchen': '🔪',
  'takeout-box': '🥡',
  'soft-serve': '🍦',
  soy: '🫘',

  // ── Beverages ─────────────────────────────────────
  beer: '🍺',
  'beer-bottle': '🍺',
  cafe: '☕',
  coffee: '☕',
  'coffee-maker': '☕',
  champagne: '🥂',
  'champagne-bottle': '🍾',
  cocktail: '🍸',
  'tropical-cocktail': '🍹',
  drink: '🥤',
  'food-and-drink': '🍽️',
  highball: '🥃',
  pitcher: '🫗',
  'soda-bottle': '🥤',
  teapot: '🫖',
  wine: '🍷',
  'wine-bottle': '🍷',
  coaster: '🍽️',
  tumbler: '🥃',

  // ── Clothing & Accessories ────────────────────────
  backpack: '🎒',
  belt: '👔',
  bikini: '👙',
  boot: '🥾',
  bra: '👙',
  coat: '🧥',
  dress: '👗',
  glasses: '👓',
  sunglasses: '🕶️',
  handbag: '👜',
  hanger: '🪝',
  hat: '🧢',
  'baseball-cap': '🧢',
  lipstick: '💄',
  'makeup-brush': '💄',
  necktie: '👔',
  pants: '👖',
  perfume: '🧴',
  scarf: '🧣',
  shirt: '👕',
  'long-sleeve-shirt': '👕',
  tshirt: '👕',
  shoe: '👟',
  pump: '👠',
  shorts: '🩳',
  skirt: '👗',
  sock: '🧦',
  suit: '🤵',
  suitcase: '🧳',
  underwear: '🩲',
  'watch-analog': '⌚',

  // ── Nature & Animals ──────────────────────────────
  butterfly: '🦋',
  cat: '🐱',
  cow: '🐄',
  crab: '🦀',
  dog: '🐕',
  donkey: '🫏',
  duck: '🦆',
  elephant: '🐘',
  fish: '🐟',
  hare: '🐇',
  pig: '🐷',
  sheep: '🐑',
  snake: '🐍',
  spider: '🕷️',
  tortoise: '🐢',
  whale: '🐋',
  bee: '🐝',
  shell: '🐚',
  leaf: '🍃',
  'leaf-monstera': '🌿',
  clover: '☘️',
  'clover-four-leaf': '🍀',
  daisy: '🌼',
  tulip: '🌷',
  'potted-plant': '🪴',
  seed: '🌱',
  cactus: '🌵',
  tree: '🌳',
  'conifer-tree': '🌲',
  'christmas-tree': '🎄',
  'palm-tree': '🌴',
  'forest-fire': '🔥',
  mountains: '🏔️',
  volcano: '🌋',
  sun: '☀️',
  sunrise: '🌅',
  sunset: '🌇',
  moon: '🌙',
  snowflake: '❄️',
  rainbow: '🌈',
  wind: '💨',
  water: '💧',
  'ringed-planet': '🪐',

  // ── Weather ───────────────────────────────────────
  cloudy: '☁️',
  fog: '🌫️',
  hail: '🌨️',
  storm: '⛈️',
  'partly-cloudy-night': '☁️',
  rain: '🌧️',
  sleet: '🌨️',
  'partly-cloudy-day': '⛅',
  hurricane: '🌀',
  tornado: '🌪️',
  earthquake: '🌍',
  flood: '🌊',

  // ── Sports & Games ────────────────────────────────
  archery: '🏹',
  baseball: '⚾',
  basketball: '🏀',
  bowling: '🎳',
  football: '🏈',
  golf: '⛳',
  soccer: '⚽',
  snorkel: '🤿',
  trophy: '🏆',
  target: '🎯',
  bullseye: '🎯',
  'chess-bishop': '♝',
  'chess-king': '♚',
  'chess-knight': '♞',
  'chess-pawn': '♟️',
  'chess-queen': '♛',
  'chess-rook': '♜',
  die1: '🎲',
  die2: '🎲',
  die3: '🎲',
  die4: '🎲',
  die5: '🎲',
  die6: '🎲',
  'game-pawn': '♟️',
  'video-game': '🎮',
  'video-game-classic': '🎮',
  'video-game-joystick': '🕹️',
  cards: '🃏',
  'card-club': '♣️',
  'card-diamond': '♦️',
  'card-heart': '♥️',
  'card-spade': '♠️',
  'suit-club': '♣️',
  'suit-diamond': '♦️',
  'suit-heart': '♥️',
  'suit-spade': '♠️',
  shogi: '🎯',
  mahjong: '🀄',
  hanafuda: '🎴',
  kite: '🪁',
  balloon: '🎈',
  whistle: '📯',

  // ── Music & Audio ─────────────────────────────────
  music: '🎵',
  'music-album': '💿',
  'music-artist': '🎤',
  'note-eighth': '🎵',
  'note-half': '🎵',
  'note-quarter': '🎵',
  'note-sixteenth': '🎵',
  'note-sixteenth-beamed': '🎶',
  'note-whole': '🎵',
  playlist: '🎶',
  boombox: '📻',
  'vinyl-record': '💿',
  guitar: '🎸',
  'electric-guitar': '🎸',
  piano: '🎹',
  violin: '🎻',
  clarinet: '🎵',
  trumpet: '🎺',
  bugle: '🎺',
  'snare-drum': '🥁',
  metronome: '🎵',
  headphones: '🎧',
  headset: '🎧',
  microphone: '🎤',
  'microphone-off': '🎤',
  'volume-high': '🔊',
  'volume-off': '🔇',

  // ── Media & Playback ──────────────────────────────
  'playback-play': '▶️',
  'playback-play-button': '▶️',
  'playback-pause': '⏸️',
  'playback-stop': '⏹️',
  'playback-fast-forward': '⏩',
  'playback-rewind': '⏪',
  'playback-next': '⏭️',
  'playback-previous': '⏮️',
  'skip-backward': '⏪',
  'skip-forward': '⏩',
  iterate: '🔁',
  movie: '🎬',
  'movie-camera': '🎬',
  'movie-clapboard': '🎬',
  'movie-clapboard-play': '🎬',
  'video-camera': '📹',
  'video-camera-off': '📹',
  camera: '📷',
  'camera-off': '📷',
  'camera-roll': '📷',
  'camera-roll-portrait': '📷',
  'photo-landscape': '🖼️',
  tv: '📺',
  slideshow: '📊',
  'slideshow-play': '📊',
  slide: '📊',
  cassette: '📼',
  videotape: '📼',

  // ── Technology & Computing ────────────────────────
  computer: '💻',
  'computer-chip': '🔲',
  laptop: '💻',
  tablet: '📱',
  keyboard: '⌨️',
  'keyboard-alternate': '⌨️',
  keypad: '🔢',
  window: '🖥️',
  'command-line': '💻',
  code: '💻',
  'code-scan': '💻',
  snippet: '💻',
  git: '🔀',
  branch: '🔀',
  'branch-create': '🔀',
  'branch-fork': '🔀',
  'branch-merge': '🔀',
  'pull-request': '🔀',
  server: '🖥️',
  cloud: '☁️',
  'cloud-yes': '☁️',
  'cloud-off': '☁️',
  'cloud-no': '☁️',
  download: '⬇️',
  upload: '⬆️',
  bluetooth: '🔵',
  wifi: '📶',
  cellular: '📶',
  radio: '📻',
  'electric-plug': '🔌',
  battery: '🔋',
  'battery-charged': '🔋',
  'battery-charging': '🔋',
  cd: '💿',
  barcode: '🔲',
  extension: '🧩',
  puzzle: '🧩',

  // ── Office & Work ─────────────────────────────────
  briefcase: '💼',
  calculator: '🧮',
  calendar: '📅',
  'calendar-day': '📅',
  'calendar-week': '📅',
  'calendar-month': '📅',
  clock: '🕐',
  'clock-alternate': '🕐',
  history: '🕐',
  hourglass: '⏳',
  stopwatch: '⏱️',
  book: '📖',
  'book-closed': '📕',
  gradebook: '📗',
  bookmark: '🔖',
  'bookmark-outline': '🔖',
  library: '📚',
  school: '🏫',
  graduate: '🎓',
  print: '🖨️',
  font: '🔤',
  pen: '🖊️',
  pencil: '✏️',
  drafts: '📝',
  compose: '✏️',
  crayon: '🖍️',
  ruler: '📏',
  'set-square': '📐',
  't-square': '📐',
  cut: '✂️',
  'rubber-stamp': '📌',

  // ── Tools & Hardware ──────────────────────────────
  gear: '⚙️',
  gears: '⚙️',
  hammer: '🔨',
  wrench: '🔧',
  screwdriver: '🪛',
  'magic-wand': '🪄',
  magnet: '🧲',
  flashlight: '🔦',
  binoculars: '🔭',
  telescope: '🔭',
  microscope: '🔬',
  'push-pin': '📌',
  pin: '📌',
  'safety-pin': '🧷',
  button: '🔘',

  // ── Medical & Health ──────────────────────────────
  'first-aid-kit': '🩹',
  'first-aid': '🩹',
  pill: '💊',
  medication: '💊',
  syringe: '💉',
  stethoscope: '🩺',
  'blood-pressure': '🩸',
  crutch: '🩼',
  'pregnancy-test': '🤰',
  dna: '🧬',

  // ── Science ───────────────────────────────────────
  science: '🔬',
  chemistry: '🧪',

  // ── Building & Construction ───────────────────────
  'construction-crane': '🏗️',
  wall: '🧱',
  'arch-bridge': '🌉',
  'suspension-bridge': '🌉',
  castle: '🏰',
  'castle-japanese': '🏯',
  city: '🏙️',
  factory: '🏭',
  government: '🏛️',

  // ── Religious & Cultural Buildings ────────────────
  church: '⛪',
  mosque: '🕌',
  synagogue: '🕍',
  temple: '🛕',
  mandir: '🛕',
  torii: '⛩️',
  paifang: '⛩️',
  menorah: '🕎',

  // ── Household & Cleaning ──────────────────────────
  broom: '🧹',
  'broom-and-dustpan': '🧹',
  duster: '🧹',
  mop: '🧹',
  'mop-and-bucket': '🪣',
  'vacuum-cleaner': '🧹',
  'dish-soap': '🧴',
  sponge: '🧽',
  'scrub-brush': '🧽',
  soap: '🧼',
  'laundry-basket': '🧺',
  'laundry-detergent': '🧴',
  'laundry-dryer': '🔥',
  'laundry-washer': '🫧',
  'clothes-button': '🔘',
  'clothes-iron': '🫗',
  'spray-bottle': '🧴',
  'pump-bottle': '🧴',
  'squeeze-tube': '🧴',
  'paper-towels': '🧻',
  'facial-tissues': '🧻',

  // ── Kitchen & Appliances ──────────────────────────
  microwave: '📦',
  oven: '🔥',
  stovetop: '🔥',
  refrigerator: '🧊',
  toaster: '🍞',
  hairdryer: '💇',
  mirror: '🪞',

  // ── Outdoors & Camping ────────────────────────────
  'camping-tent': '⛺',
  'camping-trailer': '🏕️',
  fire: '🔥',
  'fire-extinguisher': '🧯',
  fireworks: '🎆',
  'confetti-ball': '🎊',
  'confetti-party-popper': '🎉',
  'shovel-and-pail': '🪣',
  umbrella: '☂️',
  'lost-and-found': '📦',

  // ── Art & Design ──────────────────────────────────
  art: '🎨',
  'paint-brush': '🖌️',
  'paint-brush-wide': '🖌️',
  'paint-bucket': '🎨',
  'paint-roller': '🎨',
  'color-palette': '🎨',
  'color-picker': '🎨',
  'color-swatch': '🎨',
  'fabric-swatch': '🎨',
  'fan-deck': '🎨',
  contrast: '🔲',
  darks: '🌑',
  lights: '🌕',
  midtones: '🌓',
  'brightness-high': '🔆',
  create: '🎨',
  sticker: '🏷️',
  feather: '🪶',

  // ── Shopping & Commerce ───────────────────────────
  shop: '🏪',
  'shopping-bag': '🛍️',
  'shopping-basket': '🛒',
  'shopping-cart': '🛒',
  bag: '👜',
  'credit-card': '💳',
  currency: '💲',
  'currency-coin': '🪙',
  cash: '💵',
  'cash-register': '💰',
  atm: '🏧',
  gift: '🎁',
  tag: '🏷️',
  'new-badge': '🆕',
  gem: '💎',
  token: '🪙',
  star: '⭐',
  'star-half': '⭐',
  'star-outline': '⭐',

  // ── Baby & Childcare ──────────────────────────────
  'baby-bottle': '🍼',
  pram: '🍼',
  stroller: '🍼',
  mobile: '🍼',

  // ── Bathroom & Personal Care ──────────────────────
  'hair-care': '💇',
  comb: '💇',
  sunscreen: '🧴',
  apron: '🧑‍🍳',

  // ── Safety & Warnings ─────────────────────────────
  barricade: '🚧',
  'traffic-cone': '🚧',
  'traffic-light': '🚦',
  bomb: '💣',
  shield: '🛡️',
  flag: '🚩',
  'flag-checkered': '🏁',
  'flag-pennant': '🏴',
  'flag-swallowtail': '🏴',
  smoking: '🚬',
  'smoking-no': '🚭',
  cigarette: '🚬',
  'hard-hat': '⛑️',
  private: '🤫',
  conceal: '🙈',

  // ── Zodiac Signs ──────────────────────────────────
  aquarius: '♒',
  aries: '♈',
  cancer: '♋',
  capricorn: '♑',
  gemini: '♊',
  leo: '♌',
  libra: '♎',
  pisces: '♓',
  sagittarius: '♐',
  scorpio: '♏',
  taurus: '♉',
  virgo: '♍',

  // ── Miscellaneous ─────────────────────────────────
  notion: '📝',
  poo: '💩',
  sword: '⚔️',
  'jack-o-lantern': '🎃',
  ornament: '🎄',
  grave: '⚰️',
  fragile: '⚠️',
  'wrapping-paper': '🎁',
  kind: '💖',
  power: '⚡',
  helm: '⚓',
  'steering-wheel': '🚗',
  gavel: '⚖️',
  'judicial-scales': '⚖️',
  badge: '🎖️',
  card: '🪪',
  stairs: '🪜',
  jar: '🫙',
  junk: '🗑️',
  delete: '🗑️',
  inbox: '📥',
  categories: '📂',
  tabs: '📑',
  'sliders-horizontal': '🎚️',
  'sliders-vertical': '🎚️',
  list: '📋',
  'list-indent': '📋',
  dairy: '🥛',
  grocery: '🛒',
  symbol: '🔣',
  subtract: '➖',
  remove: '➖',
  plus: '➕',
  add: '➕',
  walk: '🚶',
  run: '🏃',
  'litter-disposal': '🚮',
  dance: '💃',
  gym: '🏋️',
};

/**
 * Known color suffixes in Notion SVG icon filenames.
 * Filenames follow the pattern: `{name}_{color}.svg`
 */
const COLOR_SUFFIXES = new Set([
  'gray',
  'lightgray',
  'blue',
  'red',
  'green',
  'yellow',
  'pink',
  'purple',
  'orange',
  'brown',
  'default',
]);

/**
 * Strip the color suffix and .svg extension from a Notion icon filename.
 * Examples:
 *   "briefcase_gray.svg" -> "briefcase"
 *   "arrow-up_blue.svg"  -> "arrow-up"
 *   "briefcase_gray"     -> "briefcase"
 *   "briefcase.svg"      -> "briefcase"
 *   "briefcase"          -> "briefcase"
 */
export function extractBaseName(filename: string): string {
  // Strip .svg extension
  let name = filename.replace(/\.svg$/i, '');

  // Strip color suffix (last _segment if it's a known color)
  const lastUnderscore = name.lastIndexOf('_');
  if (lastUnderscore > 0) {
    const suffix = name.substring(lastUnderscore + 1).toLowerCase();
    if (COLOR_SUFFIXES.has(suffix)) {
      name = name.substring(0, lastUnderscore);
    }
  }

  return name.toLowerCase();
}

/**
 * Extract the filename from a Notion S3/CDN icon URL.
 * URLs look like:
 *   https://www.notion.so/icons/briefcase_gray.svg
 *   https://prod-files-secure.s3.us-west-2.amazonaws.com/.../briefcase_gray.svg
 *   https://www.notion.so/icons/briefcase_gray.svg?mode=dark
 */
function extractFilenameFromUrl(url: string): string | null {
  try {
    // Strip query params
    const pathPart = url.split('?')[0] ?? '';
    // Get the last path segment
    const segments = pathPart.split('/');
    const last = segments[segments.length - 1];
    if (last && last.includes('.svg')) {
      return last;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Map a Notion SVG icon URL to an emoji equivalent.
 * Returns the emoji string, or null if the icon is not a known Notion built-in.
 *
 * @param url - Full URL to a Notion SVG icon (S3 or CDN)
 * @returns Emoji string or null
 */
export function mapNotionSvgIconToEmoji(url: string): string | null {
  // Only process SVG URLs (Notion built-in icons are always SVGs)
  if (!url.includes('.svg')) return null;

  const filename = extractFilenameFromUrl(url);
  if (!filename) return null;

  const baseName = extractBaseName(filename);
  return ICON_MAP[baseName] ?? null;
}

/**
 * Map a Notion SVG icon filename to an emoji equivalent.
 * Used for backward-compat migration of existing frontmatter values.
 *
 * @param filename - Filename like "briefcase_gray.svg" or "briefcase_gray"
 * @returns Emoji string or null
 */
export function mapNotionSvgFilenameToEmoji(filename: string): string | null {
  const baseName = extractBaseName(filename);
  return ICON_MAP[baseName] ?? null;
}
